services:
  hardhat:
    build:
      context: ./hardhat
      dockerfile: dockerfile
    ports:
      - '8545:8545'
    networks:
      - testnet
    restart: unless-stopped

  react:
    build:
      context: ./react
      dockerfile: dockerfile
    ports:
      - '443:443'
    depends_on:
      - hardhat
    networks:
      - testnet
    restart: unless-stopped

networks:
  testnet:
    driver: bridge