# FROM node:lts
FROM node:20.0
# hardhat only supports lts

RUN echo "Creating working dir and copying files"
RUN mkdir /app
WORKDIR /app
COPY . .

RUN npm i
RUN npm i npx

# Compile and deploy contracts to local testnet
# https://hardhat.org/hardhat-runner/docs/guides/deploying
RUN cd contracts && npx hardhat compile

CMD ["bash", "network_deploy.sh"]